### PR TITLE
Updated example for Next.js 9.2

### PR DESCRIPTION
**Pull request by emilbryggare**
This is PR includes an updated example for Next.js 9.2. 

With Next.js 9.2 importing next-css is not necessary as CSS imports are included out of the box. The syntax for the PostCSS plugin config is also updated.

I also added a short explanation for PurgeCSS to the readme.

### CODE REVIEW

**Comment by depsimon** [comment]
Works great! Thanks

**Comment by iamkevinwolf** [comment]
According to the [default behavior](https://nextjs.org/docs/advanced-features/customizing-postcss-config#default-behavior) of the built-in PostCSS support of NextJS, there is no need to explicitly include `autoprefixed` :).

**Comment by adamwathan** [comment]
Thanks!

**Comment by nickisnoble** [comment]
A few questions:

1. Isn't PurgeCSS already included with the latest versions of tailwind?
2. Isn't [Autoprefixer already included by default](https://nextjs.org/docs/advanced-features/customizing-postcss-config) in Next 9.2?
3. Is there a way to get this working using the preferred `@tailwind` + `@apply` postCSS directive stuff?

**Comment by adamwathan** [comment]
1. PurgeCSS was not included with Tailwind on January 23 when this was last updated, so we will update this eventually. It's on our calendar as a project to start maintaining these guides in a more official way, until like last week we just didn't have enough people on the team to even consider it.

2. Autoprefixer is included by default but if you override the PostCSS config you have to add it yourself (which makes sense, since Autoprefixer is added via PostCSS and overriding the config means you want to provide your own config).

3. Not sure what you mean, all that stuff works perfectly fine with this setup.

**Comment by nickisnoble** [comment]
So it does! Thank you.

**Pull request merged**
